#!/usr/bin/env sh
#
# NAME
#   bootstrap — bootstrap the project
#
# vim: set ts=4 sw=4 sts=4 noet:

# NOTE THAT THIS FILE IS INDENTED WITH 4-SPACE HARD TABS
# as is required for <<-EOF heredocs to work.  Please keep
# it this way!
set -e
if test -n "$SHELLDEBUG"
then
	set -x
fi

if test "${CI}" = 'true'
then
	echo "::group::Build logs"
fi

unset PYTHONDEBUG
export COMPOSE_DISABLE_ENV_FILE=1
export PIP_DISABLE_PIP_VERSION_CHECK=1
export PYTHON_ROOT_USER_ACTION=ignore
export PYTHONWARNINGS=ignore

TEST_HOST=${TEST_HOST:-127.0.0.1}

docker_exec() {
	if test "${CI}" = 'true'
	then
		docker exec -t postgres "$@"
	else
		docker compose exec postgres "$@"
	fi
}

get_exposed_port() {
	if port=$(docker compose port "$1" "$2")
	then
		echo "${port#*:}"
	else
		echo "Failed to find port for $1:$2" >&2
		return 1
	fi
}

if test "$CI" != 'true'
then
	if test -e ./.venv/bin/activate
	then
		. ./.venv/bin/activate
	else
		python3 -m venv --upgrade-deps .venv
		. ./.venv/bin/activate
	fi
fi

mkdir -p build

pip install --upgrade pip

printf 'Installing package...'
pip install -e '.[dev]'
echo ' done.'

printf 'Installing pre-commit hook...'
pre-commit install --install-hooks
echo ' done.'

if test "${CI}" != 'true'
then
	printf 'Cleaning environment...'
	docker compose down --remove-orphans --volumes
	echo ' done.'

	printf 'Starting environment...'
	docker compose up --wait --wait-timeout 120
	echo ' done.'
fi

if test "${CI}" = 'true'
then
	PGPORT=5432
else
	PGPORT="$(get_exposed_port postgres 5432)"
fi

printf 'Generating .env...'
cat > .env <<EOF
export FILE_CACHE_ENABLED=no
export TEST_HOST=${TEST_HOST}
export PGHOST=${TEST_HOST}
export PGPORT=${PGPORT}
export PGDATABASE=postgres
export PGUSER=postgres
export POSTGRES_URI=postgresql://postgres@${TEST_HOST}:${PGPORT}/postgres
EOF
echo ' done.'

if test "${CI}" = 'true'
then
	echo '::endgroup::'
fi
