#!/usr/bin/env sh
#
# NAME
#   calculate-version — calculate a PEP-440 version using git
#
# vim: set ts=4 sw=4 sts=4 noet:

# NOTE THAT THIS FILE IS INDENTED WITH 4-SPACE HARD TABS
# as is required for <<-EOF heredocs to work.  Please keep
# it this way!
set -e

cmd_name='calculate-version'
usage() {
	cat<<-EOF

		Usage: $cmd_name [-hv] [-t STARTING-TAG] [VERSION-FILE]

		Calculates a PEP-440 compliant version number using the git
		utility.

		Options:
		   -h                show this message and exit
		   -v                show diagnostic output
		   -t STARTING-TAG   use STARTING-TAG as the starting point
		                     instead of HEAD
		   VERSION-FILE      write the version number to VERSION-FILE
		                     instead of 'VERSION'

	EOF
	exit 64
}

error() {
	echo "$cmd_name: ERROR - $@"
}

info() {
	if test ${verbose:-0} -gt 0
	then
		echo "$cmd_name: $@"
	fi
}

write_version() {
	if test -n "$version_file"
	then
		info "writing version to $version_file"
		echo $1 >"$version_file"
	else
		echo $1
	fi
}


verbose=0
if !  args=`getopt ht:v $*`
then
	error failed to parse arguments.
	usage
fi

set -- $args
for arg
do
	case "$arg"
	in
	-h) usage ;;
	-t) start_tag=$2
	    shift 2 ;;
	-v) verbose=1
		shift ;;
	--) shift
		break ;;
	esac
done
version_file=${1:-VERSION}

tmpdir=`mktemp -dq`
rc=$?
if test $rc -ne 0
then
	error failed to create temporary working directory: $rc.
	exit $rc
fi
trap 'rm -fr "$tmpdir"' 0

if ! command -v git >/dev/null
then
	echo 'installing git assuming alpine environment'
	apk add --update git
fi

if test -z "$start_tag"
then
	info "discovering starting tag using git"
	if ! git describe --tags --abbrev=0 >"$tmpdir/output" 2>&1
	then
		error "git describe failed, setting version to 0.0.0"
		cat "$tmpdir/output" | while
			read line
		do
			error $line
		done
		write_version '0.0.0'
		exit 0
	fi
	start_tag=`git describe --tags --abbrev=0`
fi
starting_rev=$start_tag

info "searching for merges since $start_tag"
git rev-list --merges $start_tag...HEAD >"$tmpdir/merges"
num_merges=`wc -l "$tmpdir/merges" | awk '{print $1}'`
if test $num_merges -gt 0
then
	starting_rev=`head -n 1 "$tmpdir/merges"`
fi
info "found $num_merges merges since $start_tag"

info "searching for commits since $starting_rev"
git rev-list --first-parent $starting_rev...HEAD >"$tmpdir/commits"
num_commits=`wc -l "$tmpdir/commits" | awk '{print $1}'`
info "found $num_commits commits since $starting_rev"

version=$start_tag
if test $num_merges -gt 0
then
	version="$version.post$num_merges"
fi
if test $num_commits -gt 0
then
	version="$version.dev$num_commits"
fi

info "version calculated as $version"
write_version "$version"
